//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("pegasoModel", "FK_tabella2_tabella1", "tabella1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataBase.tabella1), "tabella2", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataBase.tabella2), true)]

#endregion

namespace DataBase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pegasoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pegasoEntities object using the connection string found in the 'pegasoEntities' section of the application configuration file.
        /// </summary>
        public pegasoEntities() : base("name=pegasoEntities", "pegasoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pegasoEntities object.
        /// </summary>
        public pegasoEntities(string connectionString) : base(connectionString, "pegasoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pegasoEntities object.
        /// </summary>
        public pegasoEntities(EntityConnection connection) : base(connection, "pegasoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabella1> tabella1
        {
            get
            {
                if ((_tabella1 == null))
                {
                    _tabella1 = base.CreateObjectSet<tabella1>("tabella1");
                }
                return _tabella1;
            }
        }
        private ObjectSet<tabella1> _tabella1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabella2> tabella2
        {
            get
            {
                if ((_tabella2 == null))
                {
                    _tabella2 = base.CreateObjectSet<tabella2>("tabella2");
                }
                return _tabella2;
            }
        }
        private ObjectSet<tabella2> _tabella2;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabella1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabella1(tabella1 tabella1)
        {
            base.AddObject("tabella1", tabella1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabella2 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabella2(tabella2 tabella2)
        {
            base.AddObject("tabella2", tabella2);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pegasoModel", Name="tabella1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabella1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabella1 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tabella1 Createtabella1(global::System.Int32 id)
        {
            tabella1 tabella1 = new tabella1();
            tabella1.Id = id;
            return tabella1;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pegasoModel", "FK_tabella2_tabella1", "tabella2")]
        public EntityCollection<tabella2> tabella2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tabella2>("pegasoModel.FK_tabella2_tabella1", "tabella2");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tabella2>("pegasoModel.FK_tabella2_tabella1", "tabella2", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pegasoModel", Name="tabella2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabella2 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabella2 object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tabella2 Createtabella2(global::System.Int32 id)
        {
            tabella2 tabella2 = new tabella2();
            tabella2.id = id;
            return tabella2;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroTelefono
        {
            get
            {
                return _NumeroTelefono;
            }
            set
            {
                OnNumeroTelefonoChanging(value);
                ReportPropertyChanging("NumeroTelefono");
                _NumeroTelefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroTelefono");
                OnNumeroTelefonoChanged();
            }
        }
        private global::System.String _NumeroTelefono;
        partial void OnNumeroTelefonoChanging(global::System.String value);
        partial void OnNumeroTelefonoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pegasoModel", "FK_tabella2_tabella1", "tabella1")]
        public tabella1 tabella1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabella1>("pegasoModel.FK_tabella2_tabella1", "tabella1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabella1>("pegasoModel.FK_tabella2_tabella1", "tabella1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tabella1> tabella1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabella1>("pegasoModel.FK_tabella2_tabella1", "tabella1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tabella1>("pegasoModel.FK_tabella2_tabella1", "tabella1", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
